---
- name: install required packages
  apt: 
    name='{{ item }}'
    state=present
  with_items: '{{ sonar_required_packages }}'

- name: Download Sonar
  get_url:
    url: '{{ sonar_download_url }}'
    dest: '{{ sonar_workspace }}/{{ sonar_version_directory }}.zip'

- name: Unzip Sonar
  unarchive:
    src: '{{ sonar_workspace }}/{{ sonar_version_directory }}.zip'
    dest: /usr/local/
    copy: no
    creates: /usr/local/sonar/COPYING

- name: Move Sonar into place.
  shell: >
    mv /usr/local/{{ sonar_version_directory }} /usr/local/sonar
    creates=/usr/local/sonar/COPYING

- name: Configure SonarQube JDBC settings
  template: src=sonar.properties.j2 dest=/usr/local/sonar/conf/sonar.properties

- name: Install Sonarqube plugins
  get_url:
    url={{ item.url }}
    dest=/usr/local/sonar/extensions/plugins
  notify: restart sonar
  with_items: '{{ sonar_plugins }}'

- name: Add sonar symlinks for service management.
  file:
    src: /usr/local/sonar/bin/linux-x86-64/sonar.sh
    dest: '{{ item }}'
    state: link
  with_items:
    - /usr/bin/sonar
    - /etc/init.d/sonar

- name: Ensure Sonar is running and set to start on boot.
  service: name=sonar state=started enabled=yes

- name: Make sure Sonar is responding on the configured port.
  wait_for: port=9000 delay=3 timeout=300

- include: checkpr.yml
